#!/bin/sh
# Run with nohup so it keeps running after logging out
#PERL5LIB=/home/gribeco/lib/perl5
#export PERL5LIB
echo $$ > .pid
while true
do
  echo starting salebot
  ./salebot2.pl
  echo salebot quit
  sleep 30
done
